set_property SRC_FILE_INFO {cfile:c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0/design_1_processing_system7_0_0_in_context.xdc rfile:../../../AXI_DDR_ZC706.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0/design_1_processing_system7_0_0_in_context.xdc id:1 order:EARLY scoped_inst:design_1_i/processing_system7_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0_in_context.xdc rfile:../../../AXI_DDR_ZC706.srcs/sources_1/bd/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0_in_context.xdc id:2 order:EARLY scoped_inst:design_1_i/util_ds_buf_0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/constrs_1/new/constr.xdc rfile:../../../AXI_DDR_ZC706.srcs/constrs_1/new/constr.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/constrs_1/new/constr_01.xdc rfile:../../../AXI_DDR_ZC706.srcs/constrs_1/new/constr_01.xdc id:4} [current_design]
current_instance design_1_i/processing_system7_0
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 [get_ports {}]
current_instance
current_instance design_1_i/util_ds_buf_0
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports {}]
current_instance
set_property src_info {type:XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK25 [get_ports sys_rst]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports sys_rst]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports led]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 5 [get_ports sys_clk_p]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_pins -hierarchical *clk_ref_mmcm_gen.mmcm_i*CLKIN1]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[0]}]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[0]}]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[0]}]
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports {ddr3_dq[0]}]
set_property src_info {type:XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[1]}]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[1]}]
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[1]}]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports {ddr3_dq[1]}]
set_property src_info {type:XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[2]}]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[2]}]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[2]}]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports {ddr3_dq[2]}]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[3]}]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[3]}]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[3]}]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J4 [get_ports {ddr3_dq[3]}]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[4]}]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[4]}]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[4]}]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K1 [get_ports {ddr3_dq[4]}]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[5]}]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[5]}]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[5]}]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports {ddr3_dq[5]}]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[6]}]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[6]}]
set_property src_info {type:XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[6]}]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J5 [get_ports {ddr3_dq[6]}]
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[7]}]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[7]}]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[7]}]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K6 [get_ports {ddr3_dq[7]}]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[8]}]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[8]}]
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[8]}]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G6 [get_ports {ddr3_dq[8]}]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[9]}]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[9]}]
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[9]}]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H4 [get_ports {ddr3_dq[9]}]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[10]}]
set_property src_info {type:XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[10]}]
set_property src_info {type:XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[10]}]
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H6 [get_ports {ddr3_dq[10]}]
set_property src_info {type:XDC file:3 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[11]}]
set_property src_info {type:XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[11]}]
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[11]}]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H3 [get_ports {ddr3_dq[11]}]
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[12]}]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[12]}]
set_property src_info {type:XDC file:3 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[12]}]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G1 [get_ports {ddr3_dq[12]}]
set_property src_info {type:XDC file:3 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[13]}]
set_property src_info {type:XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[13]}]
set_property src_info {type:XDC file:3 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[13]}]
set_property src_info {type:XDC file:3 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H2 [get_ports {ddr3_dq[13]}]
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[14]}]
set_property src_info {type:XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[14]}]
set_property src_info {type:XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[14]}]
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G5 [get_ports {ddr3_dq[14]}]
set_property src_info {type:XDC file:3 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[15]}]
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[15]}]
set_property src_info {type:XDC file:3 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[15]}]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G4 [get_ports {ddr3_dq[15]}]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[16]}]
set_property src_info {type:XDC file:3 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[16]}]
set_property src_info {type:XDC file:3 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[16]}]
set_property src_info {type:XDC file:3 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E2 [get_ports {ddr3_dq[16]}]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[17]}]
set_property src_info {type:XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[17]}]
set_property src_info {type:XDC file:3 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[17]}]
set_property src_info {type:XDC file:3 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports {ddr3_dq[17]}]
set_property src_info {type:XDC file:3 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[18]}]
set_property src_info {type:XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[18]}]
set_property src_info {type:XDC file:3 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[18]}]
set_property src_info {type:XDC file:3 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D4 [get_ports {ddr3_dq[18]}]
set_property src_info {type:XDC file:3 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[19]}]
set_property src_info {type:XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[19]}]
set_property src_info {type:XDC file:3 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[19]}]
set_property src_info {type:XDC file:3 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E5 [get_ports {ddr3_dq[19]}]
set_property src_info {type:XDC file:3 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[20]}]
set_property src_info {type:XDC file:3 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[20]}]
set_property src_info {type:XDC file:3 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[20]}]
set_property src_info {type:XDC file:3 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F4 [get_ports {ddr3_dq[20]}]
set_property src_info {type:XDC file:3 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[21]}]
set_property src_info {type:XDC file:3 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[21]}]
set_property src_info {type:XDC file:3 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[21]}]
set_property src_info {type:XDC file:3 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F3 [get_ports {ddr3_dq[21]}]
set_property src_info {type:XDC file:3 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[22]}]
set_property src_info {type:XDC file:3 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[22]}]
set_property src_info {type:XDC file:3 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[22]}]
set_property src_info {type:XDC file:3 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D1 [get_ports {ddr3_dq[22]}]
set_property src_info {type:XDC file:3 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[23]}]
set_property src_info {type:XDC file:3 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[23]}]
set_property src_info {type:XDC file:3 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[23]}]
set_property src_info {type:XDC file:3 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D3 [get_ports {ddr3_dq[23]}]
set_property src_info {type:XDC file:3 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[24]}]
set_property src_info {type:XDC file:3 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[24]}]
set_property src_info {type:XDC file:3 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[24]}]
set_property src_info {type:XDC file:3 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A2 [get_ports {ddr3_dq[24]}]
set_property src_info {type:XDC file:3 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[25]}]
set_property src_info {type:XDC file:3 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[25]}]
set_property src_info {type:XDC file:3 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[25]}]
set_property src_info {type:XDC file:3 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B2 [get_ports {ddr3_dq[25]}]
set_property src_info {type:XDC file:3 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[26]}]
set_property src_info {type:XDC file:3 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[26]}]
set_property src_info {type:XDC file:3 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[26]}]
set_property src_info {type:XDC file:3 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B4 [get_ports {ddr3_dq[26]}]
set_property src_info {type:XDC file:3 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[27]}]
set_property src_info {type:XDC file:3 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[27]}]
set_property src_info {type:XDC file:3 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[27]}]
set_property src_info {type:XDC file:3 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B5 [get_ports {ddr3_dq[27]}]
set_property src_info {type:XDC file:3 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[28]}]
set_property src_info {type:XDC file:3 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[28]}]
set_property src_info {type:XDC file:3 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[28]}]
set_property src_info {type:XDC file:3 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3 [get_ports {ddr3_dq[28]}]
set_property src_info {type:XDC file:3 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[29]}]
set_property src_info {type:XDC file:3 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[29]}]
set_property src_info {type:XDC file:3 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[29]}]
set_property src_info {type:XDC file:3 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B1 [get_ports {ddr3_dq[29]}]
set_property src_info {type:XDC file:3 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[30]}]
set_property src_info {type:XDC file:3 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[30]}]
set_property src_info {type:XDC file:3 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[30]}]
set_property src_info {type:XDC file:3 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C1 [get_ports {ddr3_dq[30]}]
set_property src_info {type:XDC file:3 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[31]}]
set_property src_info {type:XDC file:3 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[31]}]
set_property src_info {type:XDC file:3 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[31]}]
set_property src_info {type:XDC file:3 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C4 [get_ports {ddr3_dq[31]}]
set_property src_info {type:XDC file:3 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[32]}]
set_property src_info {type:XDC file:3 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[32]}]
set_property src_info {type:XDC file:3 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[32]}]
set_property src_info {type:XDC file:3 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K10 [get_ports {ddr3_dq[32]}]
set_property src_info {type:XDC file:3 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[33]}]
set_property src_info {type:XDC file:3 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[33]}]
set_property src_info {type:XDC file:3 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[33]}]
set_property src_info {type:XDC file:3 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L9 [get_ports {ddr3_dq[33]}]
set_property src_info {type:XDC file:3 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[34]}]
set_property src_info {type:XDC file:3 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[34]}]
set_property src_info {type:XDC file:3 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[34]}]
set_property src_info {type:XDC file:3 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12 [get_ports {ddr3_dq[34]}]
set_property src_info {type:XDC file:3 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[35]}]
set_property src_info {type:XDC file:3 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[35]}]
set_property src_info {type:XDC file:3 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[35]}]
set_property src_info {type:XDC file:3 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J9 [get_ports {ddr3_dq[35]}]
set_property src_info {type:XDC file:3 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[36]}]
set_property src_info {type:XDC file:3 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[36]}]
set_property src_info {type:XDC file:3 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[36]}]
set_property src_info {type:XDC file:3 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K11 [get_ports {ddr3_dq[36]}]
set_property src_info {type:XDC file:3 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[37]}]
set_property src_info {type:XDC file:3 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[37]}]
set_property src_info {type:XDC file:3 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[37]}]
set_property src_info {type:XDC file:3 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L10 [get_ports {ddr3_dq[37]}]
set_property src_info {type:XDC file:3 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[38]}]
set_property src_info {type:XDC file:3 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[38]}]
set_property src_info {type:XDC file:3 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[38]}]
set_property src_info {type:XDC file:3 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J10 [get_ports {ddr3_dq[38]}]
set_property src_info {type:XDC file:3 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[39]}]
set_property src_info {type:XDC file:3 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[39]}]
set_property src_info {type:XDC file:3 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[39]}]
set_property src_info {type:XDC file:3 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L7 [get_ports {ddr3_dq[39]}]
set_property src_info {type:XDC file:3 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[40]}]
set_property src_info {type:XDC file:3 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[40]}]
set_property src_info {type:XDC file:3 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[40]}]
set_property src_info {type:XDC file:3 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F14 [get_ports {ddr3_dq[40]}]
set_property src_info {type:XDC file:3 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[41]}]
set_property src_info {type:XDC file:3 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[41]}]
set_property src_info {type:XDC file:3 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[41]}]
set_property src_info {type:XDC file:3 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports {ddr3_dq[41]}]
set_property src_info {type:XDC file:3 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[42]}]
set_property src_info {type:XDC file:3 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[42]}]
set_property src_info {type:XDC file:3 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[42]}]
set_property src_info {type:XDC file:3 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports {ddr3_dq[42]}]
set_property src_info {type:XDC file:3 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[43]}]
set_property src_info {type:XDC file:3 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[43]}]
set_property src_info {type:XDC file:3 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[43]}]
set_property src_info {type:XDC file:3 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G16 [get_ports {ddr3_dq[43]}]
set_property src_info {type:XDC file:3 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[44]}]
set_property src_info {type:XDC file:3 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[44]}]
set_property src_info {type:XDC file:3 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[44]}]
set_property src_info {type:XDC file:3 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports {ddr3_dq[44]}]
set_property src_info {type:XDC file:3 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[45]}]
set_property src_info {type:XDC file:3 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[45]}]
set_property src_info {type:XDC file:3 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[45]}]
set_property src_info {type:XDC file:3 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports {ddr3_dq[45]}]
set_property src_info {type:XDC file:3 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[46]}]
set_property src_info {type:XDC file:3 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[46]}]
set_property src_info {type:XDC file:3 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[46]}]
set_property src_info {type:XDC file:3 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D13 [get_ports {ddr3_dq[46]}]
set_property src_info {type:XDC file:3 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[47]}]
set_property src_info {type:XDC file:3 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[47]}]
set_property src_info {type:XDC file:3 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[47]}]
set_property src_info {type:XDC file:3 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports {ddr3_dq[47]}]
set_property src_info {type:XDC file:3 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[48]}]
set_property src_info {type:XDC file:3 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[48]}]
set_property src_info {type:XDC file:3 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[48]}]
set_property src_info {type:XDC file:3 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15 [get_ports {ddr3_dq[48]}]
set_property src_info {type:XDC file:3 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[49]}]
set_property src_info {type:XDC file:3 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[49]}]
set_property src_info {type:XDC file:3 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[49]}]
set_property src_info {type:XDC file:3 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports {ddr3_dq[49]}]
set_property src_info {type:XDC file:3 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[50]}]
set_property src_info {type:XDC file:3 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[50]}]
set_property src_info {type:XDC file:3 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[50]}]
set_property src_info {type:XDC file:3 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D16 [get_ports {ddr3_dq[50]}]
set_property src_info {type:XDC file:3 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[51]}]
set_property src_info {type:XDC file:3 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[51]}]
set_property src_info {type:XDC file:3 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[51]}]
set_property src_info {type:XDC file:3 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E16 [get_ports {ddr3_dq[51]}]
set_property src_info {type:XDC file:3 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[52]}]
set_property src_info {type:XDC file:3 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[52]}]
set_property src_info {type:XDC file:3 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[52]}]
set_property src_info {type:XDC file:3 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports {ddr3_dq[52]}]
set_property src_info {type:XDC file:3 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[53]}]
set_property src_info {type:XDC file:3 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[53]}]
set_property src_info {type:XDC file:3 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[53]}]
set_property src_info {type:XDC file:3 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports {ddr3_dq[53]}]
set_property src_info {type:XDC file:3 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[54]}]
set_property src_info {type:XDC file:3 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[54]}]
set_property src_info {type:XDC file:3 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[54]}]
set_property src_info {type:XDC file:3 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D14 [get_ports {ddr3_dq[54]}]
set_property src_info {type:XDC file:3 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[55]}]
set_property src_info {type:XDC file:3 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[55]}]
set_property src_info {type:XDC file:3 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[55]}]
set_property src_info {type:XDC file:3 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports {ddr3_dq[55]}]
set_property src_info {type:XDC file:3 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[56]}]
set_property src_info {type:XDC file:3 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[56]}]
set_property src_info {type:XDC file:3 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[56]}]
set_property src_info {type:XDC file:3 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B12 [get_ports {ddr3_dq[56]}]
set_property src_info {type:XDC file:3 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[57]}]
set_property src_info {type:XDC file:3 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[57]}]
set_property src_info {type:XDC file:3 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[57]}]
set_property src_info {type:XDC file:3 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C12 [get_ports {ddr3_dq[57]}]
set_property src_info {type:XDC file:3 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[58]}]
set_property src_info {type:XDC file:3 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[58]}]
set_property src_info {type:XDC file:3 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[58]}]
set_property src_info {type:XDC file:3 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A12 [get_ports {ddr3_dq[58]}]
set_property src_info {type:XDC file:3 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[59]}]
set_property src_info {type:XDC file:3 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[59]}]
set_property src_info {type:XDC file:3 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[59]}]
set_property src_info {type:XDC file:3 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports {ddr3_dq[59]}]
set_property src_info {type:XDC file:3 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[60]}]
set_property src_info {type:XDC file:3 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[60]}]
set_property src_info {type:XDC file:3 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[60]}]
set_property src_info {type:XDC file:3 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A13 [get_ports {ddr3_dq[60]}]
set_property src_info {type:XDC file:3 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[61]}]
set_property src_info {type:XDC file:3 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[61]}]
set_property src_info {type:XDC file:3 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[61]}]
set_property src_info {type:XDC file:3 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B11 [get_ports {ddr3_dq[61]}]
set_property src_info {type:XDC file:3 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[62]}]
set_property src_info {type:XDC file:3 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[62]}]
set_property src_info {type:XDC file:3 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[62]}]
set_property src_info {type:XDC file:3 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C14 [get_ports {ddr3_dq[62]}]
set_property src_info {type:XDC file:3 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dq[63]}]
set_property src_info {type:XDC file:3 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dq[63]}]
set_property src_info {type:XDC file:3 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15_T_DCI [get_ports {ddr3_dq[63]}]
set_property src_info {type:XDC file:3 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B14 [get_ports {ddr3_dq[63]}]
set_property src_info {type:XDC file:3 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[13]}]
set_property src_info {type:XDC file:3 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[13]}]
set_property src_info {type:XDC file:3 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[13]}]
set_property src_info {type:XDC file:3 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A10 [get_ports {ddr3_addr[13]}]
set_property src_info {type:XDC file:3 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[12]}]
set_property src_info {type:XDC file:3 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[12]}]
set_property src_info {type:XDC file:3 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[12]}]
set_property src_info {type:XDC file:3 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H12 [get_ports {ddr3_addr[12]}]
set_property src_info {type:XDC file:3 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[11]}]
set_property src_info {type:XDC file:3 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[11]}]
set_property src_info {type:XDC file:3 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[11]}]
set_property src_info {type:XDC file:3 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B7 [get_ports {ddr3_addr[11]}]
set_property src_info {type:XDC file:3 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[10]}]
set_property src_info {type:XDC file:3 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[10]}]
set_property src_info {type:XDC file:3 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[10]}]
set_property src_info {type:XDC file:3 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D6 [get_ports {ddr3_addr[10]}]
set_property src_info {type:XDC file:3 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[9]}]
set_property src_info {type:XDC file:3 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[9]}]
set_property src_info {type:XDC file:3 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[9]}]
set_property src_info {type:XDC file:3 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J8 [get_ports {ddr3_addr[9]}]
set_property src_info {type:XDC file:3 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[8]}]
set_property src_info {type:XDC file:3 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[8]}]
set_property src_info {type:XDC file:3 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[8]}]
set_property src_info {type:XDC file:3 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B10 [get_ports {ddr3_addr[8]}]
set_property src_info {type:XDC file:3 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[7]}]
set_property src_info {type:XDC file:3 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[7]}]
set_property src_info {type:XDC file:3 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[7]}]
set_property src_info {type:XDC file:3 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E8 [get_ports {ddr3_addr[7]}]
set_property src_info {type:XDC file:3 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[6]}]
set_property src_info {type:XDC file:3 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[6]}]
set_property src_info {type:XDC file:3 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[6]}]
set_property src_info {type:XDC file:3 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F9 [get_ports {ddr3_addr[6]}]
set_property src_info {type:XDC file:3 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[5]}]
set_property src_info {type:XDC file:3 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[5]}]
set_property src_info {type:XDC file:3 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[5]}]
set_property src_info {type:XDC file:3 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B6 [get_ports {ddr3_addr[5]}]
set_property src_info {type:XDC file:3 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[4]}]
set_property src_info {type:XDC file:3 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[4]}]
set_property src_info {type:XDC file:3 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[4]}]
set_property src_info {type:XDC file:3 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D11 [get_ports {ddr3_addr[4]}]
set_property src_info {type:XDC file:3 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[3]}]
set_property src_info {type:XDC file:3 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[3]}]
set_property src_info {type:XDC file:3 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[3]}]
set_property src_info {type:XDC file:3 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A9 [get_ports {ddr3_addr[3]}]
set_property src_info {type:XDC file:3 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[2]}]
set_property src_info {type:XDC file:3 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[2]}]
set_property src_info {type:XDC file:3 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[2]}]
set_property src_info {type:XDC file:3 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E11 [get_ports {ddr3_addr[2]}]
set_property src_info {type:XDC file:3 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[1]}]
set_property src_info {type:XDC file:3 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[1]}]
set_property src_info {type:XDC file:3 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[1]}]
set_property src_info {type:XDC file:3 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B9 [get_ports {ddr3_addr[1]}]
set_property src_info {type:XDC file:3 line:489 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_addr[0]}]
set_property src_info {type:XDC file:3 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_addr[0]}]
set_property src_info {type:XDC file:3 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[0]}]
set_property src_info {type:XDC file:3 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E10 [get_ports {ddr3_addr[0]}]
set_property src_info {type:XDC file:3 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_ba[2]}]
set_property src_info {type:XDC file:3 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ba[2]}]
set_property src_info {type:XDC file:3 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[2]}]
set_property src_info {type:XDC file:3 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A7 [get_ports {ddr3_ba[2]}]
set_property src_info {type:XDC file:3 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_ba[1]}]
set_property src_info {type:XDC file:3 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ba[1]}]
set_property src_info {type:XDC file:3 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[1]}]
set_property src_info {type:XDC file:3 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H7 [get_ports {ddr3_ba[1]}]
set_property src_info {type:XDC file:3 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_ba[0]}]
set_property src_info {type:XDC file:3 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ba[0]}]
set_property src_info {type:XDC file:3 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[0]}]
set_property src_info {type:XDC file:3 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F8 [get_ports {ddr3_ba[0]}]
set_property src_info {type:XDC file:3 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_ras_n}]
set_property src_info {type:XDC file:3 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ras_n}]
set_property src_info {type:XDC file:3 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ras_n}]
set_property src_info {type:XDC file:3 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H11 [get_ports {ddr3_ras_n}]
set_property src_info {type:XDC file:3 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_cas_n}]
set_property src_info {type:XDC file:3 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_cas_n}]
set_property src_info {type:XDC file:3 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cas_n}]
set_property src_info {type:XDC file:3 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E7 [get_ports {ddr3_cas_n}]
set_property src_info {type:XDC file:3 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_we_n}]
set_property src_info {type:XDC file:3 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_we_n}]
set_property src_info {type:XDC file:3 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_we_n}]
set_property src_info {type:XDC file:3 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F7 [get_ports {ddr3_we_n}]
set_property src_info {type:XDC file:3 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_reset_n}]
set_property src_info {type:XDC file:3 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_reset_n}]
set_property src_info {type:XDC file:3 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports {ddr3_reset_n}]
set_property src_info {type:XDC file:3 line:534 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports {ddr3_reset_n}]
set_property src_info {type:XDC file:3 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_cke[0]}]
set_property src_info {type:XDC file:3 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_cke[0]}]
set_property src_info {type:XDC file:3 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cke[0]}]
set_property src_info {type:XDC file:3 line:540 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D10 [get_ports {ddr3_cke[0]}]
set_property src_info {type:XDC file:3 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_odt[0]}]
set_property src_info {type:XDC file:3 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_odt[0]}]
set_property src_info {type:XDC file:3 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_odt[0]}]
set_property src_info {type:XDC file:3 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G7 [get_ports {ddr3_odt[0]}]
set_property src_info {type:XDC file:3 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:XDC file:3 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:XDC file:3 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:XDC file:3 line:552 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J11 [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:XDC file:3 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[0]}]
set_property src_info {type:XDC file:3 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[0]}]
set_property src_info {type:XDC file:3 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[0]}]
set_property src_info {type:XDC file:3 line:558 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports {ddr3_dm[0]}]
set_property src_info {type:XDC file:3 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[1]}]
set_property src_info {type:XDC file:3 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[1]}]
set_property src_info {type:XDC file:3 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[1]}]
set_property src_info {type:XDC file:3 line:564 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F2 [get_ports {ddr3_dm[1]}]
set_property src_info {type:XDC file:3 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[2]}]
set_property src_info {type:XDC file:3 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[2]}]
set_property src_info {type:XDC file:3 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[2]}]
set_property src_info {type:XDC file:3 line:570 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E1 [get_ports {ddr3_dm[2]}]
set_property src_info {type:XDC file:3 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[3]}]
set_property src_info {type:XDC file:3 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[3]}]
set_property src_info {type:XDC file:3 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[3]}]
set_property src_info {type:XDC file:3 line:576 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2 [get_ports {ddr3_dm[3]}]
set_property src_info {type:XDC file:3 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[4]}]
set_property src_info {type:XDC file:3 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[4]}]
set_property src_info {type:XDC file:3 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[4]}]
set_property src_info {type:XDC file:3 line:582 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L12 [get_ports {ddr3_dm[4]}]
set_property src_info {type:XDC file:3 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[5]}]
set_property src_info {type:XDC file:3 line:586 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[5]}]
set_property src_info {type:XDC file:3 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[5]}]
set_property src_info {type:XDC file:3 line:588 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {ddr3_dm[5]}]
set_property src_info {type:XDC file:3 line:591 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[6]}]
set_property src_info {type:XDC file:3 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[6]}]
set_property src_info {type:XDC file:3 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[6]}]
set_property src_info {type:XDC file:3 line:594 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C16 [get_ports {ddr3_dm[6]}]
set_property src_info {type:XDC file:3 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dm[7]}]
set_property src_info {type:XDC file:3 line:598 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dm[7]}]
set_property src_info {type:XDC file:3 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[7]}]
set_property src_info {type:XDC file:3 line:600 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C11 [get_ports {ddr3_dm[7]}]
set_property src_info {type:XDC file:3 line:603 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO DONTCARE [get_ports {sys_clk_p}]
set_property src_info {type:XDC file:3 line:604 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {sys_clk_p}]
set_property src_info {type:XDC file:3 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H9 [get_ports {sys_clk_p}]
set_property src_info {type:XDC file:3 line:608 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO DONTCARE [get_ports {sys_clk_n}]
set_property src_info {type:XDC file:3 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {sys_clk_n}]
set_property src_info {type:XDC file:3 line:610 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G9 [get_ports {sys_clk_n}]
set_property src_info {type:XDC file:3 line:613 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:XDC file:3 line:614 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:XDC file:3 line:615 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:XDC file:3 line:616 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K3 [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:XDC file:3 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:XDC file:3 line:620 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:XDC file:3 line:621 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:XDC file:3 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:XDC file:3 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:XDC file:3 line:626 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:XDC file:3 line:627 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:XDC file:3 line:628 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:XDC file:3 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:XDC file:3 line:632 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:XDC file:3 line:633 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:XDC file:3 line:634 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H1 [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:XDC file:3 line:637 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:XDC file:3 line:638 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:XDC file:3 line:639 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:XDC file:3 line:640 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E6 [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:XDC file:3 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:XDC file:3 line:644 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:XDC file:3 line:645 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:XDC file:3 line:646 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D5 [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:XDC file:3 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:XDC file:3 line:650 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:XDC file:3 line:651 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:XDC file:3 line:652 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A5 [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:XDC file:3 line:655 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:XDC file:3 line:656 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:XDC file:3 line:657 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:XDC file:3 line:658 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A4 [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:XDC file:3 line:661 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:XDC file:3 line:662 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:XDC file:3 line:663 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:XDC file:3 line:664 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L8 [get_ports {ddr3_dqs_p[4]}]
set_property src_info {type:XDC file:3 line:667 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:XDC file:3 line:668 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:XDC file:3 line:669 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:XDC file:3 line:670 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K8 [get_ports {ddr3_dqs_n[4]}]
set_property src_info {type:XDC file:3 line:673 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:XDC file:3 line:674 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:XDC file:3 line:675 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:XDC file:3 line:676 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G12 [get_ports {ddr3_dqs_p[5]}]
set_property src_info {type:XDC file:3 line:679 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:XDC file:3 line:680 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:XDC file:3 line:681 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:XDC file:3 line:682 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F12 [get_ports {ddr3_dqs_n[5]}]
set_property src_info {type:XDC file:3 line:685 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:XDC file:3 line:686 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:XDC file:3 line:687 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:XDC file:3 line:688 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F17 [get_ports {ddr3_dqs_p[6]}]
set_property src_info {type:XDC file:3 line:691 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:XDC file:3 line:692 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:XDC file:3 line:693 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:XDC file:3 line:694 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {ddr3_dqs_n[6]}]
set_property src_info {type:XDC file:3 line:697 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:XDC file:3 line:698 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:XDC file:3 line:699 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:XDC file:3 line:700 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports {ddr3_dqs_p[7]}]
set_property src_info {type:XDC file:3 line:703 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:XDC file:3 line:704 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:XDC file:3 line:705 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:XDC file:3 line:706 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports {ddr3_dqs_n[7]}]
set_property src_info {type:XDC file:3 line:709 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:XDC file:3 line:710 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:XDC file:3 line:711 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:XDC file:3 line:712 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G10 [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:XDC file:3 line:715 export:INPUT save:INPUT read:READ} [current_design]
set_property VCCAUX_IO HIGH [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:XDC file:3 line:716 export:INPUT save:INPUT read:READ} [current_design]
set_property SLEW FAST [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:XDC file:3 line:717 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:XDC file:3 line:718 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F10 [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A17 [get_ports led]
set_property src_info {type:XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK25 [get_ports reset]
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H9 [get_ports clk_p]
set_property src_info {type:XDC file:4 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G9 [get_ports clk_n]
