# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# XDC: new/constr_01.xdc

# Block Designs: bd/design_v3/design_v3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3 || ORIG_REF_NAME==design_v3} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_fsm_v3_0_0/design_v3_fsm_v3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_fsm_v3_0_0 || ORIG_REF_NAME==design_v3_fsm_v3_0_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_processing_system7_0_0/design_v3_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_processing_system7_0_0 || ORIG_REF_NAME==design_v3_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_mig_7series_0_0/design_v3_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_mig_7series_0_0 || ORIG_REF_NAME==design_v3_mig_7series_0_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_debounce_0_1/design_v3_debounce_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_debounce_0_1 || ORIG_REF_NAME==design_v3_debounce_0_1} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_debounce_n_0_0/design_v3_debounce_n_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_debounce_n_0_0 || ORIG_REF_NAME==design_v3_debounce_n_0_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_xbar_0/design_v3_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_xbar_0 || ORIG_REF_NAME==design_v3_xbar_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_ps7_0_axi_periph_0/design_v3_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_v3_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_rst_ps7_0_50M_0/design_v3_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_v3_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_12_0/design_v3_axi_gpio_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_12_0 || ORIG_REF_NAME==design_v3_axi_gpio_12_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_6_0/design_v3_axi_gpio_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_6_0 || ORIG_REF_NAME==design_v3_axi_gpio_6_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_7_0/design_v3_axi_gpio_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_7_0 || ORIG_REF_NAME==design_v3_axi_gpio_7_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_13_0/design_v3_axi_gpio_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_13_0 || ORIG_REF_NAME==design_v3_axi_gpio_13_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_14_0/design_v3_axi_gpio_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_14_0 || ORIG_REF_NAME==design_v3_axi_gpio_14_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_8_0/design_v3_axi_gpio_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_8_0 || ORIG_REF_NAME==design_v3_axi_gpio_8_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_9_0/design_v3_axi_gpio_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_9_0 || ORIG_REF_NAME==design_v3_axi_gpio_9_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_15_0/design_v3_axi_gpio_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_15_0 || ORIG_REF_NAME==design_v3_axi_gpio_15_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_16_0/design_v3_axi_gpio_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_16_0 || ORIG_REF_NAME==design_v3_axi_gpio_16_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_17_0/design_v3_axi_gpio_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_17_0 || ORIG_REF_NAME==design_v3_axi_gpio_17_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_18_0/design_v3_axi_gpio_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_18_0 || ORIG_REF_NAME==design_v3_axi_gpio_18_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_0_0/design_v3_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_0_0 || ORIG_REF_NAME==design_v3_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_19_0/design_v3_axi_gpio_19_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_19_0 || ORIG_REF_NAME==design_v3_axi_gpio_19_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_1_0/design_v3_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_1_0 || ORIG_REF_NAME==design_v3_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_20_0/design_v3_axi_gpio_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_20_0 || ORIG_REF_NAME==design_v3_axi_gpio_20_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_2_0/design_v3_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_2_0 || ORIG_REF_NAME==design_v3_axi_gpio_2_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_3_0/design_v3_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_3_0 || ORIG_REF_NAME==design_v3_axi_gpio_3_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_21_0/design_v3_axi_gpio_21_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_21_0 || ORIG_REF_NAME==design_v3_axi_gpio_21_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_22_0/design_v3_axi_gpio_22_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_22_0 || ORIG_REF_NAME==design_v3_axi_gpio_22_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_10_0/design_v3_axi_gpio_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_10_0 || ORIG_REF_NAME==design_v3_axi_gpio_10_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_4_0/design_v3_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_4_0 || ORIG_REF_NAME==design_v3_axi_gpio_4_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_5_0/design_v3_axi_gpio_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_5_0 || ORIG_REF_NAME==design_v3_axi_gpio_5_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_11_0/design_v3_axi_gpio_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_11_0 || ORIG_REF_NAME==design_v3_axi_gpio_11_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_23_0/design_v3_axi_gpio_23_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_23_0 || ORIG_REF_NAME==design_v3_axi_gpio_23_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_24_0/design_v3_axi_gpio_24_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_24_0 || ORIG_REF_NAME==design_v3_axi_gpio_24_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_25_0/design_v3_axi_gpio_25_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_25_0 || ORIG_REF_NAME==design_v3_axi_gpio_25_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_axi_gpio_26_0/design_v3_axi_gpio_26_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_axi_gpio_26_0 || ORIG_REF_NAME==design_v3_axi_gpio_26_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_tier2_xbar_0_0/design_v3_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_tier2_xbar_0_0 || ORIG_REF_NAME==design_v3_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_tier2_xbar_1_0/design_v3_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_tier2_xbar_1_0 || ORIG_REF_NAME==design_v3_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_tier2_xbar_2_0/design_v3_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_tier2_xbar_2_0 || ORIG_REF_NAME==design_v3_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_tier2_xbar_3_0/design_v3_tier2_xbar_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_tier2_xbar_3_0 || ORIG_REF_NAME==design_v3_tier2_xbar_3_0} -quiet] -quiet

# IP: bd/design_v3/ip/design_v3_auto_pc_0/design_v3_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_v3_auto_pc_0 || ORIG_REF_NAME==design_v3_auto_pc_0} -quiet] -quiet

# XDC: bd/design_v3/design_v3_ooc.xdc
