# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/design_v3/ip/design_v3_axi_gpio_23_0/design_v3_axi_gpio_23_0.xci
# IP: The module: 'design_v3_axi_gpio_23_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/design_v3/ip/design_v3_axi_gpio_23_0/design_v3_axi_gpio_23_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_v3_axi_gpio_23_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/design_v3/ip/design_v3_axi_gpio_23_0/design_v3_axi_gpio_23_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_v3_axi_gpio_23_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/design_v3/ip/design_v3_axi_gpio_23_0/design_v3_axi_gpio_23_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_v3_axi_gpio_23_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/design_v3/ip/design_v3_axi_gpio_23_0/design_v3_axi_gpio_23_0.xci
# IP: The module: 'design_v3_axi_gpio_23_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/design_v3/ip/design_v3_axi_gpio_23_0/design_v3_axi_gpio_23_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_v3_axi_gpio_23_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/design_v3/ip/design_v3_axi_gpio_23_0/design_v3_axi_gpio_23_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_v3_axi_gpio_23_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/design_v3/ip/design_v3_axi_gpio_23_0/design_v3_axi_gpio_23_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_v3_axi_gpio_23_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
