# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/axi_ddr_design/ip/axi_ddr_design_axi_gpio_6_0/axi_ddr_design_axi_gpio_6_0.xci
# IP: The module: 'axi_ddr_design_axi_gpio_6_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/axi_ddr_design/ip/axi_ddr_design_axi_gpio_6_0/axi_ddr_design_axi_gpio_6_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ddr_design_axi_gpio_6_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/axi_ddr_design/ip/axi_ddr_design_axi_gpio_6_0/axi_ddr_design_axi_gpio_6_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ddr_design_axi_gpio_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/axi_ddr_design/ip/axi_ddr_design_axi_gpio_6_0/axi_ddr_design_axi_gpio_6_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ddr_design_axi_gpio_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/axi_ddr_design/ip/axi_ddr_design_axi_gpio_6_0/axi_ddr_design_axi_gpio_6_0.xci
# IP: The module: 'axi_ddr_design_axi_gpio_6_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/axi_ddr_design/ip/axi_ddr_design_axi_gpio_6_0/axi_ddr_design_axi_gpio_6_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ddr_design_axi_gpio_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/axi_ddr_design/ip/axi_ddr_design_axi_gpio_6_0/axi_ddr_design_axi_gpio_6_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ddr_design_axi_gpio_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Projet/Desktop/Recherche/gallay_DDR_ZC706/workspace/AXI_DDR_ZC706/AXI_DDR_ZC706.srcs/sources_1/bd/axi_ddr_design/ip/axi_ddr_design_axi_gpio_6_0/axi_ddr_design_axi_gpio_6_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_ddr_design_axi_gpio_6_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
